added test report and upload it regardless of success or fail

diff --git a/.github/workflows/windowsBuild.yml b/.github/workflows/windowsBuild.yml
--- a/.github/workflows/windowsBuild.yml
+++ b/.github/workflows/windowsBuild.yml
@@ -41,8 +41,22 @@ jobs:
 
       - name: Run Unit Tests
         run: |
-          ./build/tests/RNGTests.exe
+          mkdir -p build/test-results
+          ./build/tests/RNGTests.exe --gtest_output=xml:build/test-results/RNGTests.xml
         shell: bash
+        continue-on-error: true
+
+      - name: Upload Test Results
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: build/test-results
+
+      - name: Fail if tests failed
+        if: ${{ steps.run_tests.outcome != 'success' }}
+        run: |
+          echo "Some tests failed!"
+          exit 1
 
       - name: Upload built game
         uses: actions/upload-artifact@v4
